In [35]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [36]:
# Importing the dataset
dataset = pd.read_csv('50_Startups.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 4 ].values

In [37]:
dataset.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [38]:
X[:,[0,1,2]] = X[:,[0,1,2]].astype(int)

In [39]:
X

array([[165349, 136897, 471784, 'New York'],
       [162597, 151377, 443898, 'California'],
       [153441, 101145, 407934, 'Florida'],
       [144372, 118671, 383199, 'New York'],
       [142107, 91391, 366168, 'Florida'],
       [131876, 99814, 362861, 'New York'],
       [134615, 147198, 127716, 'California'],
       [130298, 145530, 323876, 'Florida'],
       [120542, 148718, 311613, 'New York'],
       [123334, 108679, 304981, 'California'],
       [101913, 110594, 229160, 'Florida'],
       [100671, 91790, 249744, 'California'],
       [93863, 127320, 249839, 'Florida'],
       [91992, 135495, 252664, 'California'],
       [119943, 156547, 256512, 'Florida'],
       [114523, 122616, 261776, 'New York'],
       [78013, 121597, 264346, 'California'],
       [94657, 145077, 282574, 'New York'],
       [91749, 114175, 294919, 'Florida'],
       [86419, 153514, 0, 'New York'],
       [76253, 113867, 298664, 'California'],
       [78389, 153773, 299737, 'New York'],
       [73994, 1227

In [23]:
y = y.astype(int)

In [24]:
y

array([192261, 191792, 191050, 182901, 166187, 156991, 156122, 155752,
       152211, 149759, 146121, 144259, 141585, 134307, 132602, 129917,
       126992, 125370, 124266, 122776, 118474, 111313, 110352, 108733,
       108552, 107404, 105733, 105008, 103282, 101004,  99937,  97483,
        97427,  96778,  96712,  96479,  90708,  89949,  81229,  81005,
        78239,  77798,  71498,  69758,  65200,  64926,  49490,  42559,
        35673,  14681])

# Encoding Categorical Data

In [41]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder = LabelEncoder()
X[:, 3] = labelencoder.fit_transform(X[:, 3])
onehotencoder = OneHotEncoder(categorical_features = [3])
X = onehotencoder.fit_transform(X).toarray()

/Users/kalyani/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/Users/kalyani/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [42]:
X = X[:, 1:]

In [43]:
X

array([[0.00000e+00, 1.00000e+00, 1.65349e+05, 1.36897e+05, 4.71784e+05],
       [0.00000e+00, 0.00000e+00, 1.62597e+05, 1.51377e+05, 4.43898e+05],
       [1.00000e+00, 0.00000e+00, 1.53441e+05, 1.01145e+05, 4.07934e+05],
       [0.00000e+00, 1.00000e+00, 1.44372e+05, 1.18671e+05, 3.83199e+05],
       [1.00000e+00, 0.00000e+00, 1.42107e+05, 9.13910e+04, 3.66168e+05],
       [0.00000e+00, 1.00000e+00, 1.31876e+05, 9.98140e+04, 3.62861e+05],
       [0.00000e+00, 0.00000e+00, 1.34615e+05, 1.47198e+05, 1.27716e+05],
       [1.00000e+00, 0.00000e+00, 1.30298e+05, 1.45530e+05, 3.23876e+05],
       [0.00000e+00, 1.00000e+00, 1.20542e+05, 1.48718e+05, 3.11613e+05],
       [0.00000e+00, 0.00000e+00, 1.23334e+05, 1.08679e+05, 3.04981e+05],
       [1.00000e+00, 0.00000e+00, 1.01913e+05, 1.10594e+05, 2.29160e+05],
       [0.00000e+00, 0.00000e+00, 1.00671e+05, 9.17900e+04, 2.49744e+05],
       [1.00000e+00, 0.00000e+00, 9.38630e+04, 1.27320e+05, 2.49839e+05],
       [0.00000e+00, 0.00000e+00, 9.19

In [44]:
X = X.astype(int)

In [46]:
X

array([[     0,      1, 165349, 136897, 471784],
       [     0,      0, 162597, 151377, 443898],
       [     1,      0, 153441, 101145, 407934],
       [     0,      1, 144372, 118671, 383199],
       [     1,      0, 142107,  91391, 366168],
       [     0,      1, 131876,  99814, 362861],
       [     0,      0, 134615, 147198, 127716],
       [     1,      0, 130298, 145530, 323876],
       [     0,      1, 120542, 148718, 311613],
       [     0,      0, 123334, 108679, 304981],
       [     1,      0, 101913, 110594, 229160],
       [     0,      0, 100671,  91790, 249744],
       [     1,      0,  93863, 127320, 249839],
       [     0,      0,  91992, 135495, 252664],
       [     1,      0, 119943, 156547, 256512],
       [     0,      1, 114523, 122616, 261776],
       [     0,      0,  78013, 121597, 264346],
       [     0,      1,  94657, 145077, 282574],
       [     1,      0,  91749, 114175, 294919],
       [     0,      1,  86419, 153514,      0],
       [     0,     

In [47]:
from sklearn.model_selection import train_test_split

In [49]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Fitting Multiple Linear Regression to Training Set

In [50]:
from sklearn.linear_model import LinearRegression

In [51]:
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

# Predicting the Test Set Results

In [52]:
y_predicted = regressor.predict(X_test)

In [53]:
y_predicted

array([103015.24646784, 132581.94062687, 132448.09397395,  71975.74395634,
       178537.52007852, 116161.05196902,  67851.47761322,  98791.74112204,
       113969.41004647, 167921.22416078])

In [56]:
y_predicted = y_predicted.astype(int)
y_predicted

array([103015, 132581, 132448,  71975, 178537, 116161,  67851,  98791,
       113969, 167921])

In [57]:
y_test = y_test.astype(int)
y_test

array([103282, 144259, 146121,  77798, 191050, 105008,  81229,  97483,
       110352, 166187])